require 'bundler/setup'
require 'rubygems'
require 'xp5k'
require 'erb'
require 'pp'

load 'config/deploy.rb' 

XP5K::Config.load

myxp = XP5K::XPM.new(:logger => logger)

myxp.define_job({
  :resources  => ["nodes=4, walltime=5"],
  :sites      => %w( rennes ),
  :types      => ["deploy"],
  :name       => "cassandra",
  :command    => "sleep 86400"
})

myxp.define_deployment({
  :environment    => "wheezy-x64-nfs",
  :jobs           => %w{ cassandra },
  :key            => File.read("#{ssh_public}"),
})


role :cassandra do
  myxp.get_deployed_nodes('cassandra', kavlan="#{vlan}")
end

role :frontend do
  %w(rennes)
end


desc 'Submit jobs'
task :submit do
  myxp.submit
end

desc 'Deploy with Kadeploy'
task :deploy  do
  myxp.deploy
end


namespace :cassandra do

  desc 'Deploy Cassandra on nodes'
  task :default do
    puppet
    generate
    modules::install
    transfer
    apply
  end

  desc 'Generate Cassandra config file' 
  task :generate do
    template = File.read("templates/cassandra.erb")
    renderer = ERB.new(template)
    @cassandra_name = "cassandra_cluster"
    @cassandra_seeds = myxp.get_deployed_nodes('cassandra', kavlan="#{vlan}").slice(0,4)
    generate = renderer.result(binding)
    myFile = File.open("tmp/cassandra.pp", "w")
    myFile.write(generate)
    myFile.close
  end

=begin
  desc 'Prepare environment'
  task :prepare, :roles => [:frontend] do
  set :user, "#{g5k_user}"
    run "https_proxy='http://proxy:3128' git clone https://github.com/gini/puppet-cassandra.git modules/cassandra"
    run "https_proxy='http://proxy:3128' git clone https://github.com/puppetlabs/puppetlabs-stdlib.git modules/stdlib" 
    run "https_proxy='http://proxy:3128' git clone https://github.com/puppetlabs/puppetlabs-apt.git modules/apt" 
  end
=end
  
  desc 'Puppet install'
  task :puppet, :roles => [:cassandra] do
    set :user, "root"
    run "apt-get install -y puppet"
  end

  namespace :modules do
    desc 'Install Cassandra module'
    task :install, :roles => [:cassandra] do
      set :user, "root"
      run "https_proxy='http://proxy:3128' http_proxy='http://proxy:3128' puppet module install gini/cassandra"
   end

    desc 'Uninstall Cassandra module'
    task :uninstall, :roles => [:cassandra] do
      set :user, "root"
      run "https_proxy='http://proxy:3128' http_proxy='http://proxy:3128' puppet module uninstall gini/cassandra"
   end

  end

  desc 'Transfer the puppet recipe'
  task :transfer, :roles => [:cassandra] do
    set :user, "root"
    upload("tmp/cassandra.pp","/tmp/cassandra.pp", :via => :scp)  
  end


  desc 'Apply recipe'
  task :apply, :roles => [:cassandra] do
    set :user, "root"
    run "http_proxy='http://proxy:3128' https_proxy='http://proxy:3128' FACTER_osfamily='Debian' puppet apply /tmp/cassandra.pp -d "
  end

end
desc 'Remove all running jobs'
task :clean do
  logger.debug "Clean all Grid'5000 running jobs..."
  myxp.clean
end

